config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inputs
  resources :kinds
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "inputs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :kind
  belongs_to :user

  def to_s
    data
  end

end

app/models/kind.rb
class Kind < ApplicationRecord
has_many :input
  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inputs, dependent: :destroy

  def to_s
    pseudonym
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: %i[ show edit update destroy ]

  # GET /inputs or /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1 or /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs or /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: "Input crée avec succès." }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1 or /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: "Input modifié avec succès." }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1 or /inputs/1.json
  def destroy
    @input.destroy!

    respond_to do |format|
      format.html { redirect_to inputs_path, status: :see_other, notice: "Input supprimé avec succès." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def input_params
      params.expect(input: [ :data, :kind_id, :user_id ])
    end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy!

    respond_to do |format|
      format.html { redirect_to kinds_path, status: :see_other, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.expect(kind: [ :name ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :pseudonym, :photo ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/inputs/_form.html.erb
<%= simple_form_for(@input) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :data %>
    <%= f.association :kind, include_blank: false %>
    <%= link_to "Ajouter un type d'input", new_kind_path %>

    <%= f.association :user, collection: [current_user], include_blank: false%>
  </div>

  <div class="form-actions btn btn-light mt-3 p-0">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/inputs/_input.html.erb
<div id="<%= dom_id input %>">

<div class="card" style="width: 18rem;">
  <div class="card-body">

  <p>
    <strong>Data :</strong>
    <%= input.data %>
  </p>

  <p>
    <strong>Type :</strong>
    <%= input.kind %>
  </p>

  <p>
    <strong>Crée par :</strong>
    <%= link_to input.user %>
  </p>

  <p>
  <strong>Crée le :</strong>
 <%= input.created_at.day %> / <%= input.created_at.month %> / <%= input.created_at.year %>

</p>

</div>
</div>

</div>

app/views/inputs/edit.html.erb
<% content_for :title, "Editing input" %>

<h1>Editing input</h1>

<%= render "form", input: @input %>

<br>

<div>
  <%= link_to "Voir cette input", @input %> |
  <%= link_to "Retour", inputs_path %>
</div>

app/views/inputs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Inputs" %>

<h1>Tous les Inputs</h1>

  <div class="row">

    <% @inputs.each do |input| %>
      <div class="col-xl-4 col-md-6 mt-5">
        <%= render input %>
          <p class="mt-3">
        <%= link_to "Voir cette input", input %>
      </p>
      </div>
    <% end %>

  </div>

<div class="mt-4">
<%= link_to "Nouveau input", new_input_path %>
</div>

app/views/inputs/new.html.erb
<% content_for :title, "Nouveau Input" %>

<h1>Nouveau Input</h1>

<%= render "form", input: @input %>

<br>

<div>
  <%= link_to "Retour", inputs_path %>
</div>

app/views/inputs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @input %>

<div>
  <% if user_signed_in? && current_user == @input.user %>
    <%= link_to "Modifier cette input", edit_input_path(@input) %> |
  <% end %>

  <%= link_to "Retour", inputs_path %>
  <br>
  <div class="btn btn-danger mt-4" >
  <% if user_signed_in? && current_user == @input.user %>
    <%= button_to "Supprimer", @input, method: :delete, data: { confirm: "Es-tu sûr ?" }, class:'back' %>
  <% end %>
  </div>
</div>

app/views/kinds/_form.html.erb
<%= simple_form_for(@kind) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/kinds/_kind.html.erb
<div id="<%= dom_id kind %>">
  <p>
    <strong>type : </strong>
    <%= kind.name %>
  </p>

</div>

app/views/kinds/edit.html.erb
<% content_for :title, "Editing kind" %>

<h1>Modification du type</h1>

<%= render "form", kind: @kind %>

<br>

<div>
  <%= link_to "Voir ce type", @kind %> |
  <%= link_to "Retour", kinds_path %>
</div>

app/views/kinds/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Type" %>

<h1>Type</h1>

<div id="kinds">
  <% @kinds.each do |kind| %>
    <%= render kind %>
    <p>
      <%= link_to "Voir ce type", kind %>
    </p>
  <% end %>
</div>

<%= link_to "Nouveau type", new_kind_path %>

app/views/kinds/new.html.erb
<% content_for :title, "New kind" %>

<h1>Nouveau type</h1>

<%= render "form", kind: @kind %>

<br>

<div>
  <%= link_to "Retour", kinds_path %>
</div>


<div>
  <%= link_to "Créer un Input", new_input_path %>

</div>

app/views/kinds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @kind %>

<div>
  <%= link_to "Modifier ce type", edit_kind_path(@kind) %> |
  <%= link_to "Retour", kinds_path %>

  <%= button_to "Supprimer ce type", @kind, method: :delete %>
</div>


<div>
  <%= link_to "Créer un Input", new_input_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Input" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

        <!-- Grotesk -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&display=swap" rel="stylesheet">

    <!-- Lemon Milk -->
    <link href="https://fonts.cdnfonts.com/css/lemon-milk" rel="stylesheet">


    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <header>

  <div class="header-container">
<div class="header-container">

<div>
<img src="app/assets/images/inputapia-logo.png">

</div>


    <div class="link-header">
      <h2>
        <%= link_to "INPUTOPIA", inputs_path %>
      </h2>
    </div>

    <div class="link-header">
      <h6>
        <%= link_to "Créer un Input", new_input_path %>
      </h6>
    </div>
</div>
<div class="header-container align-item-center">
    <div  class="link-header">
    <% if user_signed_in? %>
    <h6>
      <%= link_to current_user.email, user_path(current_user) %>
    </h6>
  <% end %>

    </div>
    <div class='btn btn-danger'>
    <%= button_to(
        "Déconnexion",
        destroy_user_session_path,
        method: :delete, class:'back'
      ) %>
    </div>
  </div>
  </div>


  </header>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <main class="container">
  <%= yield %>
  </main>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :pseudonym %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <hr>
    <%= render user %>
    <p>
      <%= link_to "Voir cet utilisateur", user %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>



<div>
  <%= link_to "Créer un Input", new_input_path %>

</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>


<h2>Inputs créées</h2>
<div class="mt-4">
<% @user.inputs.each do |input| %>
  <div class="mt-3">
  <li>
  <%= link_to input %><br>
  </li>
</div>
<% end %>
</div>


<div class="mt-3">


<div class="mt-3">
<%= link_to "Retour", users_path %>
</div>

</div>